### ISSUE TITLE
Failed to get D-Bus connection: No such file or directory

### ISSUE THREAD

**Issue by karlkfi** [tozd/docker-ubuntu-systemd#1] opened 2015-09-11 22:50 UTC
Trying to use this in a boot2docker VM fails:

```
$ docker run -d --name xxx -v /tmp/cgroup:/sys/fs/cgroup -v /tmp/run:/run:rw tozd/ubuntu-systemd
7fb5deb8052274d64d4b962a091e229988079fcdd7c1ecb0587541f11af37618
$ docker exec -it xxx /bin/bash
root@7fb5deb80522:/# systemctl
Failed to get D-Bus connection: No such file or directory
```

Beforehand I performed the proscribed setup:

```
root@boot2docker:/home/docker# mkdir /tmp/run && mount -t tmpfs tmpfs /tmp/run
root@boot2docker:/home/docker# rm -rf /tmp/run/lock
root@boot2docker:/home/docker# mkdir /tmp/run/lock && mount -t tmpfs tmpfs /tmp/run/lock
```

I haven't had any luck using anyone else's systemd docker containers either. This is the only one that even boots when your host OS doesn't also have systemd.

Any ideas?

**Comment by karlkfi** [comment] 2015-09-11 23:19
Looks like systemd is hosed in the above example. I can't install, upgrade, configure, or remove dbus. Many apt-get calls fail trying to use systemctl.

**Comment by mitar** [comment] 2015-09-11 23:22
Have you prepared cgroup on the host at `/tmp/cgroup`?

**Comment by karlkfi** [comment] 2015-09-11 23:38
yes. forgot to include that in my paste:

```
$ mkdir -p /tmp/cgroup/systemd && mount -t cgroup systemd /tmp/cgroup/systemd -o ro,noexec,nosuid,nodev,none,name=systemd
```

**Comment by gw0** [comment] 2016-01-04 13:05
It should work if everything is mounted correctly. You should check `docker logs xxx` for errors.

Otherwise, which version of boot2docker VM are you using? Have you made any modifications to Docker image `tozd/ubuntu-systemd`?

**Comment by ducu** [comment] 2017-07-06 17:26
+1 I've got the same error, working with Docker for Windows with Linux containers so:
```
PS C:\Users\Stanciu Alexandru> docker run -d --name xxx -v C:\ubuntu-systemd\sys:/sys/fs/cgroup:ro --tmpfs /run:rw tozd/ubuntu-systemd
e9c1ca56972fdc699dab6ff2740bb8106fe3fb7c792fcf4f1c4061d2cbb89951
PS C:\Users\Stanciu Alexandru> docker exec -it xxx /bin/bash
root@e9c1ca56972f:/# systemctl --system
Failed to get D-Bus connection: Operation not permitted
root@e9c1ca56972f:/#
```

Any hints would be appreciated, thanks!

**Comment by gw0** [comment] 2017-07-09 11:11
The problem is that you need to get a valid cgroup mounted at `/sys/fs/cgroup`. With Docker for Windows/Mac this is problematic, because the host OS does not support cgroups and nothing is mounted directly. Luckily all of those solutions start a VM with a variant of Alpine Linux OS in the background and you can even use the `docker-machine` command to manipulate it directly. So figure out how to enter this VM and how to mount `cgroups` from there. Do not forget to check `docker logs xxx`.

Because such workarounds can not exist for non-native Docker deployments, I am closing this issue as wontfix.

**Closed as completed by gw0** 2017-07-09 11:11 UTC
